### ISSUE TITLE
Emojis in footer are not shown properly on Windows

### ISSUE THREAD

**Issue by XhmikosR** [sagarkarira/coronavirus-tracker-cli#65] opened 2020-03-22 08:32 UTC
Initially reported [here](https://github.com/sagarkarira/coronavirus-tracker-cli/commit/506ee3b6c927b39c8434ffb914fea0a266e9a529#r37968536)

>@sagarkarira note that the emojis don't work on Windows
>
>![image](https://user-images.githubusercontent.com/349621/77244416-42df4000-6c1d-11ea-8d48-6896818dcbc9.png)

Maybe they should respect the emoji flag like the rest of the code?

**Comment by lateparty** [comment] 2020-03-22 11:14
This is true for shells/interpreters opened through "Windows Console" i.e. native Powershell, Command Prompt, and WSL (Windows Subsystem for Linux) but the "Windows Terminal" app does display the emojis correctly in all shells/interpreters it opens.

It's a known issue I discovered a few hours ago re: this when I was using WSL and setting up my corona stats bash commands on my linux server. I did not keep the github issues but it is being tracked in the appropriate repos. Sorry that I am too lazy to go find them again.

![curl-windows-terminal-emoji](https://user-images.githubusercontent.com/20498775/77248001-40ff9600-6c8a-11ea-98c9-e9edf7af6db7.jpg)

**Comment by eabase** [comment] 2020-03-22 13:25
You need to set a different character set (i.e. the font) used in your terminal. 
This is not a bug, but a windows shell issue. Please close.

**Comment by XhmikosR** [comment] 2020-03-22 13:32
This is a valid issue with the default Windows cmd. The emojis should respect the existent flags and not display blindly, like it happens in all other places.

**Comment by eabase** [comment] 2020-03-22 13:50
> This is a valid issue with the default Windows cmd. 

Probably, but that is not an issue for this code. That is a windowism.

> The emojis should respect the existent flags and not display blindly, like it happens in all other places.

No that is not correct. If your character set doesn't support UTF-8 or Emojis, you will always get this garbage. CHange the CMD font and see for yourself.

**Comment by XhmikosR** [comment] 2020-03-22 16:23
>Probably, but that is not an issue for this code. That is a windowism.

Whatever, I give up.

@sagarkarira feel free to close this or respect the emoji flag like it's done in all other cases.

**Comment by sagarkarira** [comment] 2020-03-22 19:30
Closing this. I've removed emojis from footer text.

**Closed by sagarkarira** 2020-03-22 19:30 UTC
